Update the python code to work with hg 1.4.3.
It seems that this code amy have been written against some older version of hg that will no longer work ->

Traceback (most recent call last):
  File "../fast-export/hg-fast-export.py", line 427, in <module>
    options.statusfile,authors=a,sob=options.sob,force=options.force))
  File "../fast-export/hg-fast-export.py", line 337, in hg2git
    ui,repo=setup_repo(repourl)
  File "/home/brian/workspace/fast-export/hg2git.py", line 29, in setup_repo
    myui=ui.ui(interactive=False)
TypeError: __init__() got an unexpected keyword argument 'interactive'